const words = {
  login: 'ログイン',
  pleaseLogin: 'ログイン情報を入力してください',
  or: 'または',
  email: 'メールアドレス',
  password: 'パスワード',
  remember: '次回からログインしたままにする',
  forgot: 'パスワードを忘れましたか？',
  noAccount: 'まだアカウントをお持ちでない場合は',
  here: 'こちら',
  account: 'アカウント',
  info: '情報',
  record: '記録',
  regist: '登録',
  stable: '厩舎',
  horse: '馬匹',
  waterIntakes: '飲水量',
  feed: '餌',
  feedIntakes: '給餌量',
  exercises: '運動量',
  worker: '従業員',
  other: 'その他',
  calendar: 'カレンダー',
  board: 'ボード',
  horseName: '＊馬名',
  horseNamePlaceHolder: '馬名を入力してください。',
  horseWeight: '＊馬体重',
  horseWeightPlaceHolder: '馬体重を入力してください。(kg)',
  horseHeight: '馬体高',
  horseHeightPlaceHolder: '馬体高を入力してください。(cm)',
  horseHin: '牝馬',
  horseBo: '牡馬',
  horseSen: '騙馬',
  birthdayPlaceHolder: '       /          /',
  birthday: '生年月日',
  kindPlaceHolder: '品種を選択してください。',
  kind: '品種',
} as const

export default words
