# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task -l

  init:
    desc: "環境初期化(何度でも実行可能 - 環境を壊してしまった場合、本コマンドの再実行で修復可能)"
    cmds:
      - cmd: brew install jq
        platforms: [linux, darwin]
      - cmd: scoop install jq
        platforms: [windows]
      - cmd: task write-playground
        platforms: [linux, darwin]
      - cmd: task write-playground-windows
        platforms: [windows]
      - task: clean
      - docker compose down -v
      - docker compose --profile schemaspy down -v
      - docker compose up -d db
      - docker compose build
      - npm ci
      - echo waiting for db to be ready...
      - cmd: sleep 40
        platforms: [linux, darwin]
      - cmd: timeout /t 40
        platforms: [windows]
      - task: seed

  up:
    desc: "バックエンドサーバーを起動"
    cmds:
      - task: db-apply
      - docker compose up --build backend

  healthcheck:
    desc: "環境健全性チェック"
    cmds:
      - docker compose ps
      - npm run type-check
      - echo "✅ Health check passed"

  # ----- 内部タスク (Internal) -----

  seed:
    internal: true
    cmds:
      - cmd: |
          until docker compose run --rm backend prisma migrate reset --skip-seed --force; do
            echo "Command failed, retrying in 10 seconds..."
            sleep 10
          done
        platforms: [linux, darwin]
      - cmd: |
          :retry
          docker compose run --rm backend prisma migrate reset --skip-seed --force
          if errorlevel 1 (
            echo Command failed, retrying in 10 seconds...
            timeout /t 10
            goto retry
          )
        platforms: [windows]
      - task: db-apply
      - docker compose run --rm -e EMAIL_SILENT=true backend prisma db seed

  clean:
    internal: true
    cmds:
      - cmd: rm -rf dist node_modules prisma/client
        platforms: [linux, darwin]
      - cmd: if exist dist rd /s /q dist
        platforms: [windows]
      - cmd: if exist node_modules rd /s /q node_modules
        platforms: [windows]
      - cmd: if exist prisma\client rd /s /q prisma\client
        platforms: [windows]

  db-apply:
    internal: true
    cmds:
      - docker compose run --rm backend prisma db push

  write-playground:
    internal: true
    platforms: [linux, darwin]
    cmds:
      - |
        FILE="playground.nnb"
        if [ ! -f "$FILE" ]; then
            cat << EOF > "$FILE"
        {"cells": [{"language": "typescript", "source": ["console.log(JSON.stringify({}))"], "outputs": [{"items": [{"mime": "application/vnd.code.notebook.stdout", "value": ["{}", ""]}]}]}]}
        EOF
        fi

  write-playground-windows:
    internal: true
    platforms: [windows]
    cmds:
      - |
        if not exist playground.nnb (
          echo {"cells": [{"language": "typescript", "source": ["console.log(JSON.stringify({}))"], "outputs": [{"items": [{"mime": "application/vnd.code.notebook.stdout", "value": ["{}", ""]}]}]}]} > playground.nnb
        )

