/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * reader-web
 * reader-web
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import { orvalAxiosInstance } from '../axios/index';
export type WebComicControllerFindOne200AllOf = {
  data: FindOneWebComicOutputDto;
};

export type WebComicControllerFindOne200 = ResponseDto & WebComicControllerFindOne200AllOf;

export type WebComicControllerGetComicList200 = ResponseDto & WebComicControllerGetComicList200AllOf;

export type PaymentControllerCheckPayment200AllOf = {
  data: CheckPaymentOutputDto;
};

export type PaymentControllerCheckPayment200 = ResponseDto & PaymentControllerCheckPayment200AllOf;

export type PaymentControllerCreatePaymentIntent200AllOf = {
  data: CreatePaymentIntentOutputDto;
};

export type PaymentControllerCreatePaymentIntent200 = ResponseDto & PaymentControllerCreatePaymentIntent200AllOf;

export type AddressControllerFindOne200AllOf = {
  data: FindOneAddressOutputDto;
};

export type AddressControllerFindOne200 = ResponseDto & AddressControllerFindOne200AllOf;

export type AddressControllerFindAll200AllOf = {
  data: FindManyAddressOutputDto[];
};

export type AddressControllerFindAll200 = ResponseDto & AddressControllerFindAll200AllOf;

export type AddressControllerFindAllParams = {
  /**
   * 住所の種類
   */
  type: number;
};

export type ZipcodeControllerGetZipcodeAddress200AllOf = {
  data: GetZipcodeOutputDto;
};

export type ZipcodeControllerGetZipcodeAddress200 = ResponseDto & ZipcodeControllerGetZipcodeAddress200AllOf;

export type ZipcodeControllerGetZipcodeAddressParams = {
  /**
   * 郵便番号は必須です
   */
  zipCode: string;
};

export interface FindOneWebComicOutputDto {
  /** Comic Object JSON */
  comicObjectJson: string;
  /** 配送日 */
  deliveryDate: string;
  /** 到着予定日 */
  estimatedArrivalDate: string;
  /** 注文ハッシュID */
  orderHashedId: string;
  /** 作品が描かれたページ数 */
  pagesCount: number;
  /** 商品代金 */
  productPrice: number;
  /** 送料 */
  shippingCost: number;
  /** タイトル */
  title: string;
  /** 合計 */
  totalPrice: number;
  /** 作品数 */
  workCount: number;
}

export interface GetComicListOutputDto {
  /** 支払額 */
  allPrice: string;
  /** 到着予定日 */
  arrivalDueDateYMD: string;
  /** 注文ハッシュID */
  orderHashedId: string;
  /** 注文ステータス */
  orderStatus: string;
  /** タイトル */
  orderTitle: string;
  /** 購入経路 */
  purchaseRoute: string;
  /** 購入日時 */
  purchaseTime: string;
  /** 発送予定日 */
  sendDueDateYMD: string;
}

export type WebComicControllerGetComicList200AllOf = {
  data: GetComicListOutputDto[];
};

export interface CheckPaymentInputDto {
  /** 注文ハッシュID */
  orderHashedId: string;
}

export interface CheckPaymentOutputDto {
  /** 購入ステータス（成功をまだ受け取っていない=0、成功を受け取った=1）。 */
  isComplete: number;
}

export interface CreatePaymentIntentInputDto {
  /** 配送先住所ID */
  destinationAddressId: number;
  /** 注文者住所ID */
  orderAddressId: number;
  /** 注文ハッシュID */
  orderHashedId: string;
}

export interface CreatePaymentIntentOutputDto {
  /** クライアントシークレット */
  clientSecret: string;
}

export interface UpdateAddressDto {
  [key: string]: unknown;
}

export interface FindManyAddressOutputDto {
  /** 町名・番地 */
  address: string;
  /** 建物名 */
  addressDetail: string;
  /** 市区町村 */
  cityName: string;
  /** 名 */
  firstName: string;
  /** 名(カナ) */
  firstNameKana: string;
  /** ID */
  id: number;
  /** 姓 */
  lastName: string;
  /** 姓(カナ) */
  lastNameKana: string;
  /** 電話番号 */
  phoneNumber: string;
  /** 都道府県 */
  prefecture: string;
  /** 郵便番号 */
  zipCode: string;
}

export interface FindOneAddressOutputDto {
  /** 住所 */
  address: string;
  /** 住所詳細 */
  addressDetail: string;
  /** 市区町村名 */
  cityName: string;
  /** 名 */
  firstName: string;
  /** 名（カナ） */
  firstNameKana: string;
  /** ID */
  id: number;
  /** 姓 */
  lastName: string;
  /** 姓（カナ） */
  lastNameKana: string;
  /** 電話番号 */
  phoneNumber: string;
  /** 都道府県 */
  prefecture: string;
  /** 郵便番号 */
  zipCode: string;
}

export interface CreateAddressInputDto {
  /** 住所 */
  address: string;
  /** 詳細住所 */
  addressDetail?: string;
  /** 市区町村名 */
  cityName: string;
  /** 住所所有者の名 */
  firstName: string;
  /** 名のカナ */
  firstNameKana: string;
  /** 住所所有者の姓 */
  lastName: string;
  /** 姓のカナ */
  lastNameKana: string;
  /** 電話番号 */
  phoneNumber: string;
  /** 都道府県 */
  prefecture: string;
  /** 住所の種類 */
  type: number;
  /** 郵便番号 */
  zipCode: string;
}

export interface GetZipcodeOutputDto {
  /** 住所テキスト */
  address: string;
  /** 市区町村名 */
  cityName: string;
  /** 都道府県 */
  prefecture: string;
  /** 郵便番号 */
  zipCode: string;
}

/**
 * データ
 */
export type ResponseDtoData = { [key: string]: unknown };

export interface ResponseDto {
  /** データ */
  data: ResponseDtoData;
}

export interface ErrorResponseDto {
  error: string;
  message: string;
  statusCode: number;
}

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * テスト(何もしないエンドポイント)
 */
export const debugControllerTest = (options?: SecondParameter<typeof orvalAxiosInstance>, signal?: AbortSignal) => {
  return orvalAxiosInstance<void>({ url: `/debug/test`, method: 'GET', signal }, options);
};

export const getDebugControllerTestQueryKey = () => {
  return [`/debug/test`] as const;
};

export const getDebugControllerTestQueryOptions = <
  TData = Awaited<ReturnType<typeof debugControllerTest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof debugControllerTest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDebugControllerTestQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof debugControllerTest>>> = ({ signal }) =>
    debugControllerTest(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof debugControllerTest>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DebugControllerTestQueryResult = NonNullable<Awaited<ReturnType<typeof debugControllerTest>>>;
export type DebugControllerTestQueryError = unknown;

export const useDebugControllerTest = <
  TData = Awaited<ReturnType<typeof debugControllerTest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof debugControllerTest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDebugControllerTestQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getDebugControllerTestSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof debugControllerTest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof debugControllerTest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDebugControllerTestQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof debugControllerTest>>> = ({ signal }) =>
    debugControllerTest(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof debugControllerTest>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DebugControllerTestSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof debugControllerTest>>>;
export type DebugControllerTestSuspenseQueryError = unknown;

export const useDebugControllerTestSuspense = <
  TData = Awaited<ReturnType<typeof debugControllerTest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof debugControllerTest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDebugControllerTestSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * テスト(何もしないエンドポイント)
 */
export const debugControllerTestAuth = (options?: SecondParameter<typeof orvalAxiosInstance>, signal?: AbortSignal) => {
  return orvalAxiosInstance<void>({ url: `/debug/test-auth`, method: 'GET', signal }, options);
};

export const getDebugControllerTestAuthQueryKey = () => {
  return [`/debug/test-auth`] as const;
};

export const getDebugControllerTestAuthQueryOptions = <
  TData = Awaited<ReturnType<typeof debugControllerTestAuth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof debugControllerTestAuth>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDebugControllerTestAuthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof debugControllerTestAuth>>> = ({ signal }) =>
    debugControllerTestAuth(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof debugControllerTestAuth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DebugControllerTestAuthQueryResult = NonNullable<Awaited<ReturnType<typeof debugControllerTestAuth>>>;
export type DebugControllerTestAuthQueryError = unknown;

export const useDebugControllerTestAuth = <
  TData = Awaited<ReturnType<typeof debugControllerTestAuth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof debugControllerTestAuth>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDebugControllerTestAuthQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getDebugControllerTestAuthSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof debugControllerTestAuth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof debugControllerTestAuth>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDebugControllerTestAuthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof debugControllerTestAuth>>> = ({ signal }) =>
    debugControllerTestAuth(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof debugControllerTestAuth>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DebugControllerTestAuthSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof debugControllerTestAuth>>
>;
export type DebugControllerTestAuthSuspenseQueryError = unknown;

export const useDebugControllerTestAuthSuspense = <
  TData = Awaited<ReturnType<typeof debugControllerTestAuth>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof debugControllerTestAuth>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDebugControllerTestAuthSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * テスト(リクエスト内容確認用)
 */
export const debugControllerCheckRequest = (
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<void>({ url: `/debug/check-request`, method: 'GET', signal }, options);
};

export const getDebugControllerCheckRequestQueryKey = () => {
  return [`/debug/check-request`] as const;
};

export const getDebugControllerCheckRequestQueryOptions = <
  TData = Awaited<ReturnType<typeof debugControllerCheckRequest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof debugControllerCheckRequest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDebugControllerCheckRequestQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof debugControllerCheckRequest>>> = ({ signal }) =>
    debugControllerCheckRequest(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof debugControllerCheckRequest>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DebugControllerCheckRequestQueryResult = NonNullable<
  Awaited<ReturnType<typeof debugControllerCheckRequest>>
>;
export type DebugControllerCheckRequestQueryError = unknown;

export const useDebugControllerCheckRequest = <
  TData = Awaited<ReturnType<typeof debugControllerCheckRequest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof debugControllerCheckRequest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDebugControllerCheckRequestQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getDebugControllerCheckRequestSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof debugControllerCheckRequest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof debugControllerCheckRequest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDebugControllerCheckRequestQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof debugControllerCheckRequest>>> = ({ signal }) =>
    debugControllerCheckRequest(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof debugControllerCheckRequest>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DebugControllerCheckRequestSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof debugControllerCheckRequest>>
>;
export type DebugControllerCheckRequestSuspenseQueryError = unknown;

export const useDebugControllerCheckRequestSuspense = <
  TData = Awaited<ReturnType<typeof debugControllerCheckRequest>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof debugControllerCheckRequest>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getDebugControllerCheckRequestSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 郵便番号検索
 */
export const zipcodeControllerGetZipcodeAddress = (
  params: ZipcodeControllerGetZipcodeAddressParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<ZipcodeControllerGetZipcodeAddress200>(
    { url: `/zipcode`, method: 'GET', params, signal },
    options,
  );
};

export const getZipcodeControllerGetZipcodeAddressQueryKey = (params: ZipcodeControllerGetZipcodeAddressParams) => {
  return [`/zipcode`, ...(params ? [params] : [])] as const;
};

export const getZipcodeControllerGetZipcodeAddressQueryOptions = <
  TData = Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>,
  TError = ErrorResponseDto,
>(
  params: ZipcodeControllerGetZipcodeAddressParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getZipcodeControllerGetZipcodeAddressQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>> = ({ signal }) =>
    zipcodeControllerGetZipcodeAddress(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ZipcodeControllerGetZipcodeAddressQueryResult = NonNullable<
  Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>
>;
export type ZipcodeControllerGetZipcodeAddressQueryError = ErrorResponseDto;

/**
 * @summary 郵便番号検索
 */
export const useZipcodeControllerGetZipcodeAddress = <
  TData = Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>,
  TError = ErrorResponseDto,
>(
  params: ZipcodeControllerGetZipcodeAddressParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getZipcodeControllerGetZipcodeAddressQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getZipcodeControllerGetZipcodeAddressSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>,
  TError = ErrorResponseDto,
>(
  params: ZipcodeControllerGetZipcodeAddressParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getZipcodeControllerGetZipcodeAddressQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>> = ({ signal }) =>
    zipcodeControllerGetZipcodeAddress(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ZipcodeControllerGetZipcodeAddressSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>
>;
export type ZipcodeControllerGetZipcodeAddressSuspenseQueryError = ErrorResponseDto;

/**
 * @summary 郵便番号検索
 */
export const useZipcodeControllerGetZipcodeAddressSuspense = <
  TData = Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>,
  TError = ErrorResponseDto,
>(
  params: ZipcodeControllerGetZipcodeAddressParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof zipcodeControllerGetZipcodeAddress>>, TError, TData>
    >;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getZipcodeControllerGetZipcodeAddressSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 新しい住所を作成
 */
export const addressControllerCreate = (
  createAddressInputDto: CreateAddressInputDto,
  options?: SecondParameter<typeof orvalAxiosInstance>,
) => {
  return orvalAxiosInstance<void>(
    { url: `/address`, method: 'POST', headers: { 'Content-Type': 'application/json' }, data: createAddressInputDto },
    options,
  );
};

export const getAddressControllerCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addressControllerCreate>>,
    TError,
    { data: CreateAddressInputDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addressControllerCreate>>,
  TError,
  { data: CreateAddressInputDto },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addressControllerCreate>>,
    { data: CreateAddressInputDto }
  > = (props) => {
    const { data } = props ?? {};

    return addressControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddressControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof addressControllerCreate>>>;
export type AddressControllerCreateMutationBody = CreateAddressInputDto;
export type AddressControllerCreateMutationError = unknown;

/**
 * @summary 新しい住所を作成
 */
export const useAddressControllerCreate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addressControllerCreate>>,
    TError,
    { data: CreateAddressInputDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addressControllerCreate>>,
  TError,
  { data: CreateAddressInputDto },
  TContext
> => {
  const mutationOptions = getAddressControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary すべての住所を取得
 */
export const addressControllerFindAll = (
  params: AddressControllerFindAllParams,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<AddressControllerFindAll200>({ url: `/address`, method: 'GET', params, signal }, options);
};

export const getAddressControllerFindAllQueryKey = (params: AddressControllerFindAllParams) => {
  return [`/address`, ...(params ? [params] : [])] as const;
};

export const getAddressControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof addressControllerFindAll>>,
  TError = ErrorResponseDto,
>(
  params: AddressControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerFindAll>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAddressControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addressControllerFindAll>>> = ({ signal }) =>
    addressControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addressControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AddressControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof addressControllerFindAll>>>;
export type AddressControllerFindAllQueryError = ErrorResponseDto;

/**
 * @summary すべての住所を取得
 */
export const useAddressControllerFindAll = <
  TData = Awaited<ReturnType<typeof addressControllerFindAll>>,
  TError = ErrorResponseDto,
>(
  params: AddressControllerFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerFindAll>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAddressControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAddressControllerFindAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof addressControllerFindAll>>,
  TError = ErrorResponseDto,
>(
  params: AddressControllerFindAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof addressControllerFindAll>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAddressControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addressControllerFindAll>>> = ({ signal }) =>
    addressControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof addressControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AddressControllerFindAllSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof addressControllerFindAll>>
>;
export type AddressControllerFindAllSuspenseQueryError = ErrorResponseDto;

/**
 * @summary すべての住所を取得
 */
export const useAddressControllerFindAllSuspense = <
  TData = Awaited<ReturnType<typeof addressControllerFindAll>>,
  TError = ErrorResponseDto,
>(
  params: AddressControllerFindAllParams,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof addressControllerFindAll>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAddressControllerFindAllSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 関連するすべての住所を削除 デバック用だから本番では使っちゃダメ
 */
export const addressControllerRemoveAll = (options?: SecondParameter<typeof orvalAxiosInstance>) => {
  return orvalAxiosInstance<void>({ url: `/address`, method: 'DELETE' }, options);
};

export const getAddressControllerRemoveAllMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof addressControllerRemoveAll>>, TError, void, TContext>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof addressControllerRemoveAll>>, TError, void, TContext> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof addressControllerRemoveAll>>, void> = () => {
    return addressControllerRemoveAll(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddressControllerRemoveAllMutationResult = NonNullable<
  Awaited<ReturnType<typeof addressControllerRemoveAll>>
>;

export type AddressControllerRemoveAllMutationError = unknown;

/**
 * @summary 関連するすべての住所を削除 デバック用だから本番では使っちゃダメ
 */
export const useAddressControllerRemoveAll = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof addressControllerRemoveAll>>, TError, void, TContext>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationResult<Awaited<ReturnType<typeof addressControllerRemoveAll>>, TError, void, TContext> => {
  const mutationOptions = getAddressControllerRemoveAllMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary IDで住所を取得
 */
export const addressControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<AddressControllerFindOne200>({ url: `/address/${id}`, method: 'GET', signal }, options);
};

export const getAddressControllerFindOneQueryKey = (id: string) => {
  return [`/address/${id}`] as const;
};

export const getAddressControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof addressControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAddressControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addressControllerFindOne>>> = ({ signal }) =>
    addressControllerFindOne(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof addressControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AddressControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof addressControllerFindOne>>>;
export type AddressControllerFindOneQueryError = ErrorResponseDto;

/**
 * @summary IDで住所を取得
 */
export const useAddressControllerFindOne = <
  TData = Awaited<ReturnType<typeof addressControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addressControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAddressControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAddressControllerFindOneSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof addressControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof addressControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAddressControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addressControllerFindOne>>> = ({ signal }) =>
    addressControllerFindOne(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof addressControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AddressControllerFindOneSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof addressControllerFindOne>>
>;
export type AddressControllerFindOneSuspenseQueryError = ErrorResponseDto;

/**
 * @summary IDで住所を取得
 */
export const useAddressControllerFindOneSuspense = <
  TData = Awaited<ReturnType<typeof addressControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  id: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof addressControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAddressControllerFindOneSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary IDで住所を更新
 */
export const addressControllerUpdate = (
  id: string,
  updateAddressDto: UpdateAddressDto,
  options?: SecondParameter<typeof orvalAxiosInstance>,
) => {
  return orvalAxiosInstance<void>(
    { url: `/address/${id}`, method: 'PATCH', headers: { 'Content-Type': 'application/json' }, data: updateAddressDto },
    options,
  );
};

export const getAddressControllerUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addressControllerUpdate>>,
    TError,
    { id: string; data: UpdateAddressDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addressControllerUpdate>>,
  TError,
  { id: string; data: UpdateAddressDto },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addressControllerUpdate>>,
    { id: string; data: UpdateAddressDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return addressControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddressControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof addressControllerUpdate>>>;
export type AddressControllerUpdateMutationBody = UpdateAddressDto;
export type AddressControllerUpdateMutationError = unknown;

/**
 * @summary IDで住所を更新
 */
export const useAddressControllerUpdate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addressControllerUpdate>>,
    TError,
    { id: string; data: UpdateAddressDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addressControllerUpdate>>,
  TError,
  { id: string; data: UpdateAddressDto },
  TContext
> => {
  const mutationOptions = getAddressControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary clientSecret情報を発行
 */
export const paymentControllerCreatePaymentIntent = (
  createPaymentIntentInputDto: CreatePaymentIntentInputDto,
  options?: SecondParameter<typeof orvalAxiosInstance>,
) => {
  return orvalAxiosInstance<PaymentControllerCreatePaymentIntent200>(
    {
      url: `/payment/create-payment-intent`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPaymentIntentInputDto,
    },
    options,
  );
};

export const getPaymentControllerCreatePaymentIntentMutationOptions = <
  TError = ErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerCreatePaymentIntent>>,
    TError,
    { data: CreatePaymentIntentInputDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerCreatePaymentIntent>>,
  TError,
  { data: CreatePaymentIntentInputDto },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerCreatePaymentIntent>>,
    { data: CreatePaymentIntentInputDto }
  > = (props) => {
    const { data } = props ?? {};

    return paymentControllerCreatePaymentIntent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerCreatePaymentIntentMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerCreatePaymentIntent>>
>;
export type PaymentControllerCreatePaymentIntentMutationBody = CreatePaymentIntentInputDto;
export type PaymentControllerCreatePaymentIntentMutationError = ErrorResponseDto;

/**
 * @summary clientSecret情報を発行
 */
export const usePaymentControllerCreatePaymentIntent = <TError = ErrorResponseDto, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerCreatePaymentIntent>>,
    TError,
    { data: CreatePaymentIntentInputDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerCreatePaymentIntent>>,
  TError,
  { data: CreatePaymentIntentInputDto },
  TContext
> => {
  const mutationOptions = getPaymentControllerCreatePaymentIntentMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary stripeから飛んでくるwebhookを受け取る
 */
export const paymentControllerPaymentIntentWebhook = (options?: SecondParameter<typeof orvalAxiosInstance>) => {
  return orvalAxiosInstance<void>({ url: `/payment/webhook`, method: 'POST' }, options);
};

export const getPaymentControllerPaymentIntentWebhookMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerPaymentIntentWebhook>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof paymentControllerPaymentIntentWebhook>>, TError, void, TContext> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof paymentControllerPaymentIntentWebhook>>, void> = () => {
    return paymentControllerPaymentIntentWebhook(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerPaymentIntentWebhookMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerPaymentIntentWebhook>>
>;

export type PaymentControllerPaymentIntentWebhookMutationError = unknown;

/**
 * @summary stripeから飛んでくるwebhookを受け取る
 */
export const usePaymentControllerPaymentIntentWebhook = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerPaymentIntentWebhook>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationResult<Awaited<ReturnType<typeof paymentControllerPaymentIntentWebhook>>, TError, void, TContext> => {
  const mutationOptions = getPaymentControllerPaymentIntentWebhookMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary 決済が成功しているかどうか確認するためのAPI
 */
export const paymentControllerCheckPayment = (
  checkPaymentInputDto: CheckPaymentInputDto,
  options?: SecondParameter<typeof orvalAxiosInstance>,
) => {
  return orvalAxiosInstance<PaymentControllerCheckPayment200>(
    {
      url: `/payment/check`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: checkPaymentInputDto,
    },
    options,
  );
};

export const getPaymentControllerCheckPaymentMutationOptions = <
  TError = ErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerCheckPayment>>,
    TError,
    { data: CheckPaymentInputDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentControllerCheckPayment>>,
  TError,
  { data: CheckPaymentInputDto },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentControllerCheckPayment>>,
    { data: CheckPaymentInputDto }
  > = (props) => {
    const { data } = props ?? {};

    return paymentControllerCheckPayment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentControllerCheckPaymentMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentControllerCheckPayment>>
>;
export type PaymentControllerCheckPaymentMutationBody = CheckPaymentInputDto;
export type PaymentControllerCheckPaymentMutationError = ErrorResponseDto;

/**
 * @summary 決済が成功しているかどうか確認するためのAPI
 */
export const usePaymentControllerCheckPayment = <TError = ErrorResponseDto, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentControllerCheckPayment>>,
    TError,
    { data: CheckPaymentInputDto },
    TContext
  >;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof paymentControllerCheckPayment>>,
  TError,
  { data: CheckPaymentInputDto },
  TContext
> => {
  const mutationOptions = getPaymentControllerCheckPaymentMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary コミック一覧取得
 */
export const webComicControllerGetComicList = (
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<WebComicControllerGetComicList200>(
    { url: `/web-comic/list`, method: 'GET', signal },
    options,
  );
};

export const getWebComicControllerGetComicListQueryKey = () => {
  return [`/web-comic/list`] as const;
};

export const getWebComicControllerGetComicListQueryOptions = <
  TData = Awaited<ReturnType<typeof webComicControllerGetComicList>>,
  TError = ErrorResponseDto,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof webComicControllerGetComicList>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWebComicControllerGetComicListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof webComicControllerGetComicList>>> = ({ signal }) =>
    webComicControllerGetComicList(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof webComicControllerGetComicList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type WebComicControllerGetComicListQueryResult = NonNullable<
  Awaited<ReturnType<typeof webComicControllerGetComicList>>
>;
export type WebComicControllerGetComicListQueryError = ErrorResponseDto;

/**
 * @summary コミック一覧取得
 */
export const useWebComicControllerGetComicList = <
  TData = Awaited<ReturnType<typeof webComicControllerGetComicList>>,
  TError = ErrorResponseDto,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof webComicControllerGetComicList>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getWebComicControllerGetComicListQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getWebComicControllerGetComicListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof webComicControllerGetComicList>>,
  TError = ErrorResponseDto,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof webComicControllerGetComicList>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWebComicControllerGetComicListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof webComicControllerGetComicList>>> = ({ signal }) =>
    webComicControllerGetComicList(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof webComicControllerGetComicList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type WebComicControllerGetComicListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof webComicControllerGetComicList>>
>;
export type WebComicControllerGetComicListSuspenseQueryError = ErrorResponseDto;

/**
 * @summary コミック一覧取得
 */
export const useWebComicControllerGetComicListSuspense = <
  TData = Awaited<ReturnType<typeof webComicControllerGetComicList>>,
  TError = ErrorResponseDto,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof webComicControllerGetComicList>>, TError, TData>>;
  request?: SecondParameter<typeof orvalAxiosInstance>;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getWebComicControllerGetComicListSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 作品情報
 */
export const webComicControllerFindOne = (
  seriesHashedId: string,
  options?: SecondParameter<typeof orvalAxiosInstance>,
  signal?: AbortSignal,
) => {
  return orvalAxiosInstance<WebComicControllerFindOne200>(
    { url: `/web-comic/${seriesHashedId}`, method: 'GET', signal },
    options,
  );
};

export const getWebComicControllerFindOneQueryKey = (seriesHashedId: string) => {
  return [`/web-comic/${seriesHashedId}`] as const;
};

export const getWebComicControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof webComicControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  seriesHashedId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof webComicControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWebComicControllerFindOneQueryKey(seriesHashedId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof webComicControllerFindOne>>> = ({ signal }) =>
    webComicControllerFindOne(seriesHashedId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!seriesHashedId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof webComicControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type WebComicControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof webComicControllerFindOne>>>;
export type WebComicControllerFindOneQueryError = ErrorResponseDto;

/**
 * @summary 作品情報
 */
export const useWebComicControllerFindOne = <
  TData = Awaited<ReturnType<typeof webComicControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  seriesHashedId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof webComicControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getWebComicControllerFindOneQueryOptions(seriesHashedId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getWebComicControllerFindOneSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof webComicControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  seriesHashedId: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof webComicControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWebComicControllerFindOneQueryKey(seriesHashedId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof webComicControllerFindOne>>> = ({ signal }) =>
    webComicControllerFindOne(seriesHashedId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!seriesHashedId, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof webComicControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type WebComicControllerFindOneSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof webComicControllerFindOne>>
>;
export type WebComicControllerFindOneSuspenseQueryError = ErrorResponseDto;

/**
 * @summary 作品情報
 */
export const useWebComicControllerFindOneSuspense = <
  TData = Awaited<ReturnType<typeof webComicControllerFindOne>>,
  TError = ErrorResponseDto,
>(
  seriesHashedId: string,
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof webComicControllerFindOne>>, TError, TData>>;
    request?: SecondParameter<typeof orvalAxiosInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getWebComicControllerFindOneSuspenseQueryOptions(seriesHashedId, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
