name: development

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: install yarn packages
        uses: './.github/actions/setup-node'

      - name: Run Lint And Prettier
        run: yarn fix

      - name: Build Next.js For SSR & SSG And typedoc & storybook
        run: yarn build

      - name: chromatic deploy
        run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
