name: development

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: node_module Cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
        shell: bash
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
        shell: bash
      - run: yarn list --depth=0
        shell: bash

      - name: Run Lint And Prettier
        run: yarn fix

      - name: Build Next.js For SSR & SSG And typedoc & storybook
        run: yarn build

      - name: chromatic deploy
        run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
