name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node-version-file: .tool-versions
    secrets:
      firebase-api-key: ${{ secrets.FIREBASE_DEV_API_KEY }}
      firebase-auth-domain: ${{ secrets.FIREBASE_DEV_AUTH_DOMAIN }}
      firebase-project-id: ${{ secrets.FIREBASE_DEV_PROJECT_ID }}
      firebase-storage-bucket: ${{ secrets.FIREBASE_DEV_STORAGE_BUCKET }}
      firebase-messaging-sender-id: ${{ secrets.FIREBASE_DEV_MESSAGING_SENDER_ID }}
      firebase-app-id: ${{ secrets.FIREBASE_DEV_APP_ID }}
      firebase-measurement-id: ${{ secrets.FIREBASE_DEV_MEASUREMENT_ID }}

  license-check:
    uses: ./.github/workflows/reusable-license-check.yml
    with:
      node-version-file: .tool-versions
