name: development

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: permisson
        run: chmod +x ./android/gradlew

      - name: Build with Gradle
        run: cd ./android && ./gradlew assembleDebug
