name: development

on:
  pull_request:
    branches:
      - develop
    types: [closed]

  workflow_dispatch:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
      - run: yarn list --depth=0

      - name: volta build
        run: yarn build

      - name: permisson
        run: chmod +x ./android/gradlew
      - name: Run Android Lint
        working-directory: ./android
        run: ./gradlew lintDebug
      - name: Run Unit Test
        working-directory: ./android
        run: ./gradlew testDebug
      - name: Build with Gradle
        working-directory: ./android
        run: ./gradlew assembleDebug
      - name: Build with Gradle
        working-directory: ./android
        run: ./gradlew assembleDebug
