name: development-container-image-deploy

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - develop

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  SERVICE: ${{ vars.GCP_REPOSITORY }}
  REGION: ${{ vars.GCP_REGION }}
  IMAGE: asia.gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY }}/app:${{ github.sha }}

jobs:
  deploy:
    #NOTE: pushしたときには実行されないようにしたいので、pull_requestの条件を追加
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
          token_format: access_token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for gcloud
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.IMAGE }} -f ./.docker/Dockerfile.prod . \
            --build-arg NEXT_PUBLIC_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_API_ENDPOINT_DEV }} \
            --build-arg NEXT_PUBLIC_STORAGE_ENDPOINT=${{ secrets.NEXT_PUBLIC_STORAGE_ENDPOINT_DEV }} \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_DEV }} \
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_DEV }} \
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID_DEV }} \
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_DEV }} \
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_DEV }} \
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID_DEV }} \
            --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID_DEV }}
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
