name: development

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: node_module Cache
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
      - run: yarn list --depth=0

      - name: Run Lint And Prettier
        run: yarn fix

      - name: Build Next.js For SSR & SSG And typedoc & storybook
        run: yarn build

      #     - name: Run Variable Test
      #       run: yarn test

      - name: chromatic deploy
        run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: SSR Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ssr-build
          path: .next/
          retention-days: 3

      - name: SSG Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ssg-build
          path: out/
          retention-days: 3

      - name: StoryBook Artifact
        uses: actions/upload-artifact@v3 #ここ
        if: always()
        with:
          name: storybook-static
          path: storybook-static/
          retention-days: 3

      - name: Typedoc Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: typedocs-static
          path: typedocs-static/
          retention-days: 3
