name: Pr Auto Setting

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ${{ vars.RUNNER_LINUX }}
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1.6.2

  auto-label-branch:
    name: Label based on branch name
    runs-on: ${{ vars.RUNNER_LINUX }}
    steps:
      - name: Add label based on branch name
        uses: actions/github-script@211cb3fefb35a799baa5156f9321bb774fe56294 # v5.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.payload.pull_request.head.ref;
            console.log(`Branch name: ${branchName}`);

            console.log('Adding label based on branch name...');
            if (branchName.startsWith('feature/')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['feature']
              });
              console.log('Feature label added.');
            } else if (branchName.startsWith('bugfix/')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['bugfix']
              });
              console.log('Bugfix label added.');
            } else if (branchName.startsWith('release/')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['release']
              });
              console.log('Release label added.');
            } else if (branchName.startsWith('hotfix/')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['hotfix']
              });
              console.log('Hotfix label added.');
            } else if (branchName.startsWith('support/')) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['support']
              });
              console.log('Support label added.');
            } else {
              console.log('No matching prefix found for label addition.');
            }

  auto-label-files:
    name: Label based on changed files
    runs-on: ${{ vars.RUNNER_LINUX }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          configuration-path: '.github/labeler.yml'
