name: production

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: node_module install
        run: yarn install

      - name: SourceMap Don't generate
        run: touch .env.production && echo "GENERATE_SOURCEMAP=false" >> .env.production

      - name: Build All
        run: yarn build

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # 権限を与える
      - name: Grant permission gradlew
        run: chmod +x ./android/gradlew

      - name: Building APK for Release
        env:
          ENV_SIGN_KEYSTORE_BASE64: ${{secrets.ENV_SIGN_KEYSTORE_BASE64}}
          ENV_SIGN_KEY_ALIAS: ${{secrets.ENV_SIGN_KEY_ALIAS}}
          ENV_SIGN_KEY_PASSWORD: ${{secrets.ENV_SIGN_KEY_PASSWORD}}
          ENV_SIGN_STORE_PASSWORD: ${{secrets.ENV_SIGN_STORE_PASSWORD}}
        run: ./android/gradlew assembleRelease

      - name: SSR Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ssr-build
          path: .next/
          retention-days: 3

      - name: SSG Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ssg-build
          path: out/
          retention-days: 3

      - name: StoryBook Artifact
        uses: actions/upload-artifact@v3 #ここ
        if: always()
        with:
          name: storybook-static
          path: storybook-static/
          retention-days: 3

      - name: Typedoc Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: typedocs-static
          path: typedocs-static/
          retention-days: 3
