name: Semgrep Code Scan
'on':
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  actions: read

jobs:
  semgrep:
    name: Semgrep コード品質スキャン
    runs-on: ${{ vars.RUNNER_LINUX || 'ubuntu-24.04' }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Semgrep
        run: semgrep scan --config auto --error
