name: Semgrep コードスキャン
'on':
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  actions: read

jobs:
  semgrep:
    name: Semgrep コード品質スキャン
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Semgrep を実行
        run: semgrep scan --config auto
        continue-on-error: true
