name: TruffleHog シークレットスキャン
'on':
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  security-events: write

jobs:
  trufflehog:
    name: TruffleHog シークレットスキャン
    runs-on: ${{ vars.RUNNER_LINUX }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # v3.95.9
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified
